### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by rschuil** [v-v/BiDNN#2]
First of all my compliments for your work and thank you for making this available on Github. This was a missing piece of my puzzle and I was very glad to see that your tool does an outstanding job on my dataset.
However, I run out of memory quite quickly with this. Is there anything that can be done to use less memory or read the dataset in batches or something?

**Comment by rschuil** [comment]
Never mind. I found a solution, I think :)

**Comment by v-v** [comment]
Hello and thank you for your kind words. Glad it helped on your dataset!

The training is already done in minibatches, the only problem was that the program would load the whole dataset in memory. It's sufficient to change line 238 of bidnn.py ( https://github.com/v-v/BiDNN/blob/master/bidnn.py#L238 ) and load/provide the data directly instead of calling __iterate_minibatches__. Also bidnn.load_dataset() on line 464 would have to be removed.

I guess you already figured that out :) Feel free to reclose the ticket if so.

**Comment by rschuil** [comment]
That's exactly what I thought :) Am I correct that it would also be possible to save the model, load it again and continue training?

**Comment by v-v** [comment]
Yes, it should be possible. I don't use it myself (I usually just let it train and execute an evaluator every n epochs) but I implemented it.

**Comment by wa1618i** [comment]
Hi how is it possible to load dataset directly without calling load_dataset() ? 
Also the mention about changing line 238 means to say to set shuffle=False?
